### ISSUE TITLE
Incorrect treatment of "self supported alpine hut"

### ISSUE THREAD

**Issue by googol42** [freizeitkarte/fzk-mde-garmin#10]
Hello,

there are currently the following rules:
``tourism = alpine_hut & amenity = restaurant {name "$__ALPINEHUT__"} [0x4803 resolution 23]``
``tourism = alpine_hut {name "$__ALPINEHUT__"} [0x4804 resolution 23]``

Also there are notes denoting the former as "Bewirtschaftete Berghütten" and the later as "Selbstversorgerhütten". But this is not correct according to the (wiki)[https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dalpine_hut]. It is stated, that

> You will find food, shelter and sleeping places

in alpine_huts. Also
> Permanent human presence during the opening period from staff to provide services, if no staff use tourism=wilderness_hut, if private hut for rent use tourism=chalet

So, the comments and rules should be changed (no distinction needed). Furthermore the styles and rules should be checked to render wilderness_hut as "Selbstbverzorger Hütte".

Regards

**Comment by keenonkites** [comment]
Thanks for the hints, we'll check that for future releases.

**Comment by keenonkites** [comment]
Style files adapted for next version.
Thanks
