### ISSUE TITLE
tourism = attraction causing "problems"

### ISSUE THREAD

**Issue by googol42** [freizeitkarte/fzk-mde-garmin#11]
Hello,

I forked fzk-mde-garmin and made lots of changes for my personal map. I noted that the rules for ``tourism = attraction`` match before some other rules. E. g. there are ``waterway=waterfall`` that are also tagged as ``tourism = attraction``.

I found ``tourism = attraction`` more generic and thus moved it further down in points-master. Also, there is already an exception in the file to prevent this for ``amenity = place_of_worship``.

I suggest to move the rule to the bottom. However, this is just a suggestion. We can simply cheery-pick commit aec684b96d00a64e04b4120a6b67b9d94de92399 on a new branch and create a PR.

**Comment by keenonkites** [comment]
Well check that for a future release... thanks for the hint.

**Comment by keenonkites** [comment]
Your explanation and your solution for the problem make sense..... implemented as proposed.
Many thanks.
