### ISSUE TITLE
New Types found - use them?

### ISSUE THREAD

**Issue by googol42** [freizeitkarte/fzk-mde-garmin#12]
Hello,

I identified some more categories (see commit 8491f829d5b7d1b7942dffc22a4ee92f422823f8) and made some changes to the points-master file accordingly (see 5975e036979bd754ea0497eaea0515f7e0c8aeb6). I think these should be added as they give the user more categories on devices (btw, I tested this on a Garmin etrex 20x).

Also commit 5975e036979bd754ea0497eaea0515f7e0c8aeb6 adds/udpates some correction rules for deprecated taggings (``shop = drugstore``, ``shop = wine `` and ``shop = winery``).

Regards and thanks for you work!

**Comment by keenonkites** [comment]
I'll go into more details for a future release... thanks for the hint

**Comment by keenonkites** [comment]
Adapted as proposed, many thanks
