### ISSUE TITLE
Download *.md5 file before downloading maps

### ISSUE THREAD

**Issue by googol42** [freizeitkarte/fzk-mde-garmin#15]
Hello,

I built my own script to build my custom maps when needed. When testing new things I build the maps multiple times, which is bad (more traffic, idle time). Same is true for the ele data.

Prior to download it could be checked if the local data is up to date. For ele data the ``.info`` file can be used. For geofabrik data ``.md5`` file can be used.

However, if the "check" files are not found the download should proceed as this prevents easy modification of the download site (actually there is already a source in mt.pl neither pointing to geofabrik nor to freizeitkarte-osm.de).

**Comment by keenonkites** [comment]
If you want to rebuild maps without downloading the data again, you can just skip the fetch_* commands. If you just changed things regarding styles you can start with the build command.

For my purposes I normally use the group commands 'pmd' (for prepare map data) and 'bml' (for build map language). These options are described in short when you issue:
perl mt.pl -h -o

Cheers Patrik

**Comment by googol42** [comment]
Thanks for the hints. I did not know the 'pmd' and 'bml' command. :+1: 

My setup/workflow looks like this:
- I have a few scripts to build maps (see [googol42/garmin-osm-scripts](https://github.com/googol42/garmin-osm-scripts), build_map.sh/build_map.py) or download maps
- prior to building I edit my script to only build the maps I want (basically I uncommet the maps I want)
- the build script then builds me two map versions (one I call 'explore' map for the computer and one for my GPS device)
- although I trigger this myself, I still try to automate things

For my setup it is not worth it to check elevation data in my own scripts. But I guess, that there a few people out there doing something similar and my intention with this issue was to
- save you traffic
- and speed up build for guys like me

However, just my thoughts. If you don't think it is worth it for the project - nevermind :-)

**Comment by keenonkites** [comment]
Actually I don't think this one is worth implementing as there are possibilities to go around it by using the proper actions: if no new elevation is needed, just don't fetch it each time, leave that command out.

If I issue the 'fetch' commands I expect that the file is downloaded, even if there is a version locally already. Assuming mt.pl is checking if the remote file is newer, then I would have to implement also a 'force' parameter to download it anyway, or manually delete the file first, also suboptimal... ;-)

But as said: nevertheless many thanks for the input.

**Comment by googol42** [comment]
Alright, that fine :)
