### ISSUE TITLE
outdoorc.TYP or outdoorl.TYP maps not recognized on Garmin Oregon 550

### ISSUE THREAD

**Issue by momo42** [freizeitkarte/fzk-mde-garmin#18]
Because of https://github.com/freizeitkarte/fzk-mde-garmin/issues/17 I used the Windows Version of ReplaceType (ReplaceTyp.cmd) to convert Freizeitkarte-Deutschland.img. Sadly this didn't work out as expected.

The resulting map types 'small', 'contrast', and 'outdoor' work on my Garmin Oregon 550, but 'outdoorc' and 'outdoorl' are not recognized. The maps simply don't show up in the device menu, when put to the microsd card.

Can someone confirm outdoorc and outtoorl don't work on Garmin?

**Comment by keenonkites** [comment]
It sounds as you have the same map with different typ files simultaneously on your device... this is not possible.
Else I can just say that outdoorc and outdoorl are also working on Garmin.... you just also have to make sure that you always have the same version of map and typ file: from the same release....

**Comment by momo42** [comment]
Shame on me! You are right. I copied one Map into the Garmin-Folder and all the others into root of my MicroSD to to be able to compare them in sunlight without time consuming copy operations in between (instead just connecting device to notebook and moving files between folders). For some weird reason this worked out for all Maps but those two. Now I tried every Map on its own and all of them are working fine. Thanks for your advice and please excuse my laziness! :-)
