### ISSUE TITLE
erlaube resume für downloads

### ISSUE THREAD

**Issue by HolgerJeromin** [freizeitkarte/fzk-mde-garmin#2]
Gerade mit langsamen Verbindungen wäre es gut, wenn die Downloads unterbrechbar wären. Einfach das Kommando nochmal aufrufen sollte dann den Transfer wieder aufnehmen. curl kann das per `-C` glaub ich.

**Comment by keenonkites** [comment]
Danke für den Hint.... ich schau mir mal an, ob wir das einigermassen vernünftig in den nächsten release kriegen... für das Windows wget wird es wohl etwas entsprechendes geben.
Gruss Patrik

**Comment by keenonkites** [comment]
Es ist im develop branch mal drin, sollte dann im nächsten offiziellen Release kommen (irgendwann im Januar):
--continuedownload

**Comment by HolgerJeromin** [comment]
danke!

**Comment by keenonkites** [comment]
Keine Ursache.... hoffentlich es funktioniert für Dich so wie's erwartet ist.
