### ISSUE TITLE
tourism=bed_and_breakfast depreciated

### ISSUE THREAD

**Issue by googol42** [freizeitkarte/fzk-mde-garmin#20]
Hello,

the tag ``tourism=bed_and_breakfast`` is depreciated. Instead the following should be used: ``tourism=guest_house`` together with ``guest_house=bed_and_breakfast``. See https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dguest_house

According to taginfo (https://taginfo.openstreetmap.org/tags/?key=tourism&value=bed_and_breakfast#overview) there are around 600 nodes with this depreciated tag, so this should be considered when fixing this.

**Comment by keenonkites** [comment]
Thanks googol42.

I've adapted the style files for future versions to fetch both versions, the deprecated one and the new version.
