### ISSUE TITLE
Deprecated amenity key amenity=public_building

### ISSUE THREAD

**Issue by googol42** [freizeitkarte/fzk-mde-garmin#21]
Instead of`amenity=public_building`  `building=public` should be used

See https://wiki.openstreetmap.org/wiki/DE:Key:amenity

Cheers (and thanks for the nice map)

**Comment by keenonkites** [comment]
Thanks googol42.

Adapted the style files for future versions to reflect the tagging changes. Deprecated and new versions are considered valid.
