### ISSUE TITLE
How do a build maps for Android devices

### ISSUE THREAD

**Issue by semidark** [freizeitkarte/fzk-mde-garmin#36]
Hi,

First of all. Thank you for all of your work. I love Freizeitkarte so much that I want to use it while spending a long time on the American Continent. As there are no pre-build maps have to build the maps by my self.

For Garmin Devices and my Linux Laptop, this is obviously no issue since the fzk-mde-garmin is exactly made for this purpose. 

But how do I Build maps for my Android App Locus Maps?

Help would be very much appciated.

Thank You

**Comment by keenonkites** [comment]
Hi semidark,

thanks for your feedback and the interest in our maps.
The tool chain, or in other words the development environment, for building Android maps is at the moment not thought to be released to the public but it already has been a topic. The main reasons why we decided against releasing it were the following:

- it's a much more complex thing than the garmin mde, it's much more than issuing a few easy commands to get a map
- the requirements for the building environment (memory/disk/....) are much higher than for the garmin mde, we're not talking here about a few percents more, it's a quite big difference not that easy fullfilled on 'home equipment'
- the code is not everywhere mature enough to be release
- as we're doing this in our spare time, we were also bit afraid of having to support it, if we release it we also want to be able to react in a more or less timely manner for questions

Sorry for the negative answer, but there's at the moment nothing we can provide you to build also Android Maps.

Cheers
Patrik
