### ISSUE TITLE
Request for help with a region of France

### ISSUE THREAD

**Issue by Gabriel60410** [freizeitkarte/fzk-mde-garmin#40]
Hello to you, being a beginner I have some difficulties with the creation of the map of France. No problem with the example provided for Luxembourg, but with France, it's too large; in reality I only need the "Ile de France" region... Could you give me the steps to follow to finalize the map of France or that of the Ile de France region please?

Good for you

**Comment by keenonkites** [comment]
That actually not supported without adapting the mt.pl.
You would have to add the following line below the line number 240 (the one with the map definition for FREIZEITKARTE_LAREUNION):

`  [ 5863, 'Freizeitkarte_ILE-DE-FRANCE',              'https://download.geofabrik.de/europe/france/ile-de-france.html',                                 'ILE-DE-FRANCE',                'de', 'no_old_name',                             3, 'NA'             ],`

Then you should be able to build Ile-de-France the same way as you did for Luxembourg.

Hope this helps.
Cheers

**Comment by Gabriel60410** [comment]
Thank you ! It worked perfectly! I just changed the url in the line to https://download.geofabrik.de/europe/france/ile-de-france-latest.osm.pbf and I was able to install the map on basecamp! How did you find the list of regions on geofabrik? Thanks again !!!

**Comment by keenonkites** [comment]
If you go to https://download.geofabrik.de/ then you can browse to the country you want and for France you see the regions and can download this extract. This is also where you can grab the download link.

Glad I could help.

I'll close this count.

Cheers
