### ISSUE TITLE
Error building 

### ISSUE THREAD

**Issue by pmakowski** [freizeitkarte/fzk-mde-garmin#42]
Hi

Under Linux I did  :
`perl mt.pl bootstrap`
`perl mt.pl create Freizeitkarte_FRA`
`perl mt.pl fetch_osm Freizeitkarte_FRA`
`perl mt.pl fetch_ele Freizeitkarte_FRA`
`perl mt.pl join Freizeitkarte_FRA`
`perl mt.pl split Freizeitkarte_FRA`
`perl mt.pl build Freizeitkarte_FRA`

And I got an error  :

mt.pl - Map Tool for creating Garmin maps, 1.3.17 - 2019/04/14

Checking the Development Environment...

Action:     build
            5.  build map files (img, mdx, tdb)
Map:        Freizeitkarte_FRA (6250)
Language:   French (fr)
CodePage:   1252
Typ file:   freizeit.TYP
Style Dir:  style/fzk
Elevation:  20 m
Map type:   downloadable OSM extract
Release:    24.02 / 2402

Creating /home/philippe/Téléchargements/fzk-mde-garmin-LATEST/Freizeitkarte-Entwicklung/work/Freizeitkarte_FRA_fr/Freizeitkarte_FRA.cfg ...
Can't open /home/philippe/Téléchargements/fzk-mde-garmin-LATEST/Freizeitkarte-Entwicklung/work/Freizeitkarte_FRA/template.args: No such file or directory

can you help me ?
thanks

**Comment by keenonkites** [comment]
Hi,

Most probably you missed another error before in the 'build' action or in any other actions before.

Some ideas I have without much background information:
- FRA is quite a big map, probably you run into memory problems. If this is the case you have to use --ram option and give the process more RAM
- looking at the path I see that it contains 'accents' in the french version of 'Downloads'. I'm not sure if mt.pl is able to cope with that. Try to mov the whole fzk-mde-garmin-LATEST directory into a different path not containing any special characters

More I can't help without having more and/or complete error logs/outputs

Cheers

**Comment by pmakowski** [comment]
Thanks
setting ram value and moving into a different path not containing any special characters solved the problem
