### ISSUE TITLE
Japanese map has chinese tranposed names

### ISSUE THREAD

**Issue by twan199** [freizeitkarte/fzk-mde-garmin#43]
I used the following commands:
perl mt.pl bootstrap
perl mt.pl fetch_osm Freizeitkarte_JPN 
perl mt.pl fetch_ele Freizeitkarte_JPN
perl mt.pl join Freizeitkarte_JPN
perl mt.pl split Freizeitkarte_JPN 
perl mt.pl build Freizeitkarte_JPN
perl mt.pl nsis Freizeitkarte_JPN

This close up of Tokyo shows that instead of Tokyo, the Japanese character for Tokyo are translated using Chinese
![image](https://github.com/freizeitkarte/fzk-mde-garmin/assets/47270022/e8138f6c-a6e8-44b3-9eec-c4956cf44095)
As shown here by google translate (look at pronunciation)
![image](https://github.com/freizeitkarte/fzk-mde-garmin/assets/47270022/0254a4d9-b37c-4a0f-b11b-52dcfcc26187)

Expected behavior is like shown on geofabrik website:
![image](https://github.com/freizeitkarte/fzk-mde-garmin/assets/47270022/35d577c3-3e70-4e47-ae9e-a714022da636)

**Comment by keenonkites** [comment]
Our tools normally do not create unicode (utf8) maps as not all garmin devices support utf8 maps. This is why you see transposed characters.

There are two options for running mt.pl that will support what you want: --unicode and --ntl. Please read the details about it and how to use them on http://www.freizeitkarte-osm.de/garmin/en/development.html

You definitely have to use --unicode and most probably also --ntl to hand over an ordered list of name-tags that will be used for creating the names on the map.

Which name-tags are available you can check on openstreetmap.org, here's the link for Tokyo for example: https://www.openstreetmap.org/relation/1543125
I assume you should put name:ja-Hira in front of the tag-list. I could imagine that the following works quite well if all objects have name:ja-Hira or name:ja tags set:
... --unicode --ntl="name:ja,name:ja-Hira,name"

But as I can not read or write Japanese you have to check on your own which name-tags are those you want to use for the names on the map.

Hope that helps

**Comment by twan199** [comment]
Thanks a lot!
