### ISSUE TITLE
Flag to Throttle Downloads

### ISSUE THREAD

**Issue by teddyimsuff** [freizeitkarte/fzk-mde-garmin#6]
When downloading big maps like EUROPE it may come in handy to have a flag to throttle download speeds. 

Reason is you may want to do that in the background during the day and not use all of your available bandwidth.

Flags are: 
curl --limit-rate 123K
wget --limit-rate=123k

switch might be something like:
perl mt.pl --something --speed 123k --something-else fetch_osm MAPNAME

Teddy

**Comment by keenonkites** [comment]
I'm not sure if this really is a good idea... especially with the big maps the download time is quite long anyway.... I personally would not want to prolonge that artificially with limiting the bandwith.... then 'during the day' would might be not long enough.

But I'll see what I can do.

**Comment by keenonkites** [comment]
Is integrated in development branch.... have fun downloading at 'low' speed... :wink: 
--downloadspeed=value [k|m|g]

Cheers
Patrik
