### ISSUE TITLE
Generating elevation data

### ISSUE THREAD

**Issue by teddyimsuff** [freizeitkarte/fzk-mde-garmin#8]
Not a bug, rather a question to which I cannot find the answer in the code or on the homepage:
How can I generate elevation data for maps that are not available on " "http://develop.freizeitkarte-osm.de/" ?

**Comment by keenonkites** [comment]
We use phyghtmap to create the elevation data in the proper format with the proper boundaries:
https://wiki.openstreetmap.org/wiki/Phyghtmap
It's quite time and resource intensive to build those files and they are not rebuilt with new releases.
