### ISSUE TITLE
Building Alps

### ISSUE THREAD

**Issue by googol42** [freizeitkarte/fzk-mde-garmin#9]
Hello,

what is the correct way to build special maps, like ALPS. My guess is that one has to perform the action "create", "fetch_osm", "fetch_ele" for "FREIZEITKARTE_EUROPE". Is this correct?

Regards

**Comment by keenonkites** [comment]
The process to build maps is documented on the web page:
https://www.freizeitkarte-osm.de/garmin/en/development.html

Our ALPS map is our own extract, therefore the process is Number 2), described in more details here:
https://www.freizeitkarte-osm.de/garmin/en/development-extracts.html

If it would be a directly downloadable extract then (like DEU or CHE for example) then it falls into category 1), described in more details here
https://www.freizeitkarte-osm.de/garmin/en/development-normal.html

Hope this helps.
Cheers Patrik

**Comment by googol42** [comment]
Thanks for your response - once I found out the project was on github I forked it and mainly looked at the readme files etc... I created a Pull Request to add this to the readmes. But I think the PR need more changes...
